// GENERATED by scripts/update-ephemeris-snapshot.ts — do not edit by hand.
// The frozen build-date ephemeris ephemeris.ts prefers as its freshness layer.
import type { AstroSnapshot } from "../../scripts/update-ephemeris-snapshot.ts";

export const ASTRO_SNAPSHOT = {
	date: "2026-06-14",
	positions: [
		{
			body: "sun",
			x: 0,
			y: 0,
			angle: 1.4582549477414917,
			radius: 0,
		},
		{
			body: "earth",
			x: 205.41309396425356,
			y: 0,
			angle: 0,
			radius: 205.41309396425356,
		},
		{
			body: "mercury",
			x: -36.971302968800416,
			y: 135.0300809330616,
			angle: 1.838047025606901,
			radius: 140,
		},
		{
			body: "venus",
			x: -97.1712153860468,
			y: 155.14593094881016,
			angle: 2.130345292116015,
			radius: 183.06421001816403,
		},
		{
			body: "mars",
			x: 156.92227943539368,
			y: 174.18364744306697,
			angle: 0.8374834764191625,
			radius: 234.44518510681857,
		},
		{
			body: "jupiter",
			x: -142.5429491261181,
			y: 285.44028573998514,
			angle: 2.03394719375067,
			radius: 319.05273712804194,
		},
		{
			body: "saturn",
			x: 351.68074805732,
			y: 80.62789490276802,
			angle: 0.2253696858700005,
			radius: 360.80494174915066,
		},
		{
			body: "uranus",
			x: 184.197239606598,
			y: 365.160144998288,
			angle: 1.1036120762040031,
			radius: 408.9872303310474,
		},
		{
			body: "neptune",
			x: 439.19620321216263,
			y: 25.421156695510305,
			angle: 0.057816585406713195,
			radius: 439.93129023032327,
		},
		{
			body: "moon",
			x: 210.03959319468353,
			y: 31.663788542605428,
			angle: 1.4257097464303143,
			radius: 32,
		},
	],
} satisfies AstroSnapshot;
