#let small-cell(body) = align(center + horizon, text(size: 7pt)[#body])
#let source-cell(body) = align(left + horizon, text(size: 7pt)[#body])
#let formula-cell(body) = align(center + horizon, text(size: 7pt)[
  #math.equation(block: true, body)
])

#let scoring-rule-provenance-table() = figure(
  table(
    columns: (0.52fr, 0.68fr, 2.15fr, 0.66fr, 0.76fr, 1.18fr),
    inset: (x: 2.2pt, y: 3.2pt),
    align: center + horizon,
    stroke: none,
    table.header(
      small-cell([Method]),
      small-cell([Rank kernel]),
      small-cell([Formula]),
      small-cell([Nonzero at $|R_d| = 1$]),
      small-cell([Bounded coverage bonus]),
      source-cell([Source]),
    ),
    table.hline(stroke: 0.4pt),
    small-cell([$S_(upright("RRF"))$]),
    small-cell([reciprocal]),
    formula-cell($ sum_(i in I_d) frac(1, 60 + r_i(d)) $),
    small-cell([Yes]),
    small-cell([No]),
    source-cell([RRF @cormack2009]),
    small-cell([coverage division]),
    small-cell([reciprocal]),
    formula-cell($ S_(upright("RRF"))(d) / |R_d| $),
    small-cell([Yes]),
    small-cell([Yes]),
    source-cell([CombANZ @fox1994]),
    small-cell([$S_w$]),
    small-cell([reciprocal]),
    formula-cell($ sum_(i in I_d) frac(w_i, 60 + r_i(d)) $),
    small-cell([Yes]),
    small-cell([No]),
    source-cell([Azure weighted vector queries @azureVectorWeighting]),
    small-cell([$S_(upright("ISR"))$]),
    small-cell([inverse square]),
    formula-cell($ |R_d| sum_(i in I_d) frac(1, r_i(d)^2) $),
    small-cell([Yes]),
    small-cell([No]),
    source-cell([ISR @mourao2014]),
    small-cell([$S_(upright("logISR"))$]),
    small-cell([inverse square]),
    formula-cell($ ln(|R_d|) sum_(i in I_d) frac(1, r_i(d)^2) $),
    small-cell([No]),
    small-cell([No]),
    source-cell([logISR @mourao2014]),
    small-cell([$S_1$]),
    small-cell([reciprocal]),
    formula-cell($ S_(upright("RRF"))(d) frac(ln(|R_d| + 1), ln(2)) $),
    small-cell([Yes]),
    small-cell([No]),
    source-cell([This study]),
    small-cell([$S_(upright("sat"))$]),
    small-cell([reciprocal]),
    formula-cell($ S_(upright("RRF"))(d) (1 + a (1 - exp((1 + b - |R_d|) / t))) $),
    small-cell([Yes]),
    small-cell([Yes]),
    source-cell([This study]),
    table.hline(stroke: 0.4pt),
  ),
  kind: table,
  supplement: [Table],
  caption: [Provenance and boundary behavior for selected scoring rules, including logISR's one-retriever boundary.],
)
