"""Step 0: inspect dataset schemas before assuming any column name.

For each dataset in config/sources.yaml, fetches the SODA metadata (full
field list) and, for the Street Construction Permits dataset specifically,
pulls the distinct values of every field named in classification.yaml's
`source_fields` — with row counts — so a human can classify them instead
of guessing.

Writes config/classification.generated.yaml: every distinct value found,
pre-mapped to "UNCLASSIFIED". A human copies real category assignments
from that file into config/classification.yaml; classify.py refuses to
proceed while classification.yaml still has unresolved entries.
"""

from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

import requests
import yaml

from socrata import fetch_all, fetch_metadata

CONFIG_DIR = Path(__file__).resolve().parent.parent / "config"


def load_config() -> dict:
    return yaml.safe_load((CONFIG_DIR / "sources.yaml").read_text(encoding="utf-8"))


def load_classification_fields() -> list[str]:
    classification = yaml.safe_load(
        (CONFIG_DIR / "classification.yaml").read_text(encoding="utf-8")
    )
    return classification.get("source_fields", [])


def print_field_list(dataset_key: str, metadata: dict) -> None:
    print(f"\n=== {dataset_key}: field list ===")
    for col in metadata.get("columns", []):
        name = col.get("fieldName")
        dtype = col.get("dataTypeName")
        desc = (col.get("description") or "").strip()
        print(f"  {name!r:35} {dtype:12} {desc[:80]}")


def print_distinct_values(
    resource_url: str, dataset_id: str, field: str, session: requests.Session
) -> Counter:
    """Pull every row's value for `field` via SoQL $select/$group, so this
    stays a lightweight aggregate query rather than a full-table pull."""
    counts: Counter = Counter()
    offset = 0
    page_size = 1000
    while True:
        params = {
            "$select": f"{field}, count(1) as n",
            "$group": field,
            "$limit": page_size,
            "$offset": offset,
        }
        resp = session.get(resource_url, params=params, timeout=60)
        resp.raise_for_status()
        page = resp.json()
        if not page:
            break
        for row in page:
            counts[row.get(field)] = int(row.get("n", 0))
        offset += page_size
        if len(page) < page_size:
            break
    return counts


def main() -> None:
    config = load_config()
    fields = load_classification_fields()
    session = requests.Session()

    generated: dict[str, dict[str, str]] = {}

    for dataset_key, dataset in config["datasets"].items():
        print(f"\nFetching metadata for {dataset_key} ({dataset['dataset_id']})...")
        try:
            metadata = fetch_metadata(dataset["metadata_url"], session=session)
        except requests.RequestException as exc:
            print(f"  FAILED to fetch metadata: {exc}", file=sys.stderr)
            continue
        print_field_list(dataset_key, metadata)

        if dataset_key != "street_construction_permits":
            continue

        for field in fields:
            print(f"\n=== {dataset_key}: distinct values of '{field}' ===")
            try:
                counts = print_distinct_values(
                    dataset["resource_url"], dataset["dataset_id"], field, session
                )
            except requests.RequestException as exc:
                print(f"  FAILED to fetch distinct values: {exc}", file=sys.stderr)
                continue
            for value, n in sorted(counts.items(), key=lambda kv: -kv[1]):
                print(f"  {value!r:50} {n:>8} rows")
            generated[field] = {str(v): "UNCLASSIFIED" for v in counts}

    out_path = CONFIG_DIR / "classification.generated.yaml"
    out_path.write_text(
        "# Auto-generated by inspect_schema.py. Copy real category\n"
        "# assignments from here into classification.yaml's `mapping`.\n"
        + yaml.safe_dump(generated, sort_keys=True, allow_unicode=True),
        encoding="utf-8",
    )
    print(f"\nWrote {out_path} — review it, then update classification.yaml.")


if __name__ == "__main__":
    main()
