// Build-time generator: renders the engine-turned guilloché field ONCE at the
// default slider values and freezes it as a data: URI literal so production ships
// a flat prebaked finish (the live feTurbulence relief is the #debug alternative).
//
// PURE builder + write guard, the scripts/sitemap.ts idiom: buildGuillocheImage
// is a deterministic string builder (no canvas, no I/O — just spiral geometry to
// an inline SVG, base64-encoded), so importing this module has no filesystem side
// effect; the writeFileSync runs only under import.meta.main. The build wires
// `node scripts/render-guilloche.ts` BEFORE the SSG render so src/lib/guilloche-image.ts
// exists when dial.ts imports GUILLOCHE_IMAGE.
//
// SVG (not canvas/PNG) keeps the renderer dependency-free and deterministic: the
// guilloché is a dense rosette of phase-shifted spirals, exactly the engine-turning
// the visual spec calls for, and an SVG data URI is a valid <image href> target.
import { join } from "node:path";
import { writeGenerated } from "./write-generated.ts";

/** The guilloché renderer parameters — the prebake mirror of the #debug sliders
 *  (guilloche-section.ts SLIDERS): how dense the rosette is, how many petals, how
 *  far each spiral winds, and the stroke weight of the engraving lines. */
export interface GuillocheParams {
	/** Number of overlaid spiral curves (rosette petals). Denser → finer field. */
	petals: number;
	/** Radial turns each spiral makes from center to rim. */
	turns: number;
	/** Amplitude of the petal modulation (how pronounced the rosette lobes are). */
	amplitude: number;
	/** Stroke width of the engraved lines (SVG user units). */
	stroke: number;
}

/** Default prebake parameters — seeded near the #debug slider defaults so the
 *  baked finish matches the live relief's resting look. */
export const GUILLOCHE_DEFAULTS: GuillocheParams = {
	petals: 48,
	turns: 7,
	amplitude: 18,
	stroke: 0.6,
};

// The baked field is square and centered on the dial origin, sized to the ±500
// viewBox the dial paints it into.
const FIELD = 1000;
const RADIUS = 480;
// Samples per spiral. 240 keeps the curves smooth at dial scale while keeping the
// baked data URI compact (the live #debug relief is the high-fidelity path).
const STEPS = 240;
// Coordinate precision (decimals) in the path data. One decimal is sub-pixel at
// the ±500 viewBox and roughly halves the literal versus two.
const PRECISION = 1;

/** One spiral path, phase-shifted by `phase` radians, as an SVG path `d` string.
 *  A rose-modulated Archimedean spiral: r grows linearly with the winding angle,
 *  modulated by the petal count so neighbouring spirals interleave into the
 *  engine-turned rosette. */
function spiralPath(phase: number, params: GuillocheParams): string {
	const points: string[] = [];
	for (let i = 0; i <= STEPS; i++) {
		const t = i / STEPS;
		const theta = phase + t * params.turns * 2 * Math.PI;
		const rose = params.amplitude * Math.sin(params.petals * theta);
		const r = t * RADIUS + rose;
		const x = r * Math.cos(theta);
		const y = r * Math.sin(theta);
		points.push(`${x.toFixed(PRECISION)},${y.toFixed(PRECISION)}`);
	}
	return `M ${points.join(" L ")}`;
}

/** Build the guilloché finish as a base64-encoded SVG data URI. PURE — no file
 *  write, so importing this module is side-effect free (the sitemap.ts purity
 *  invariant). The field is a dense set of phase-shifted rose spirals stroked in
 *  a faint engraving tone over the midnight dial, the engine-turning the visual
 *  spec calls for. */
export function buildGuillocheImage(
	params: GuillocheParams = GUILLOCHE_DEFAULTS,
): string {
	const paths: string[] = [];
	for (let k = 0; k < params.petals; k++) {
		const phase = (k / params.petals) * 2 * Math.PI;
		paths.push(
			`<path d="${spiralPath(phase, params)}" fill="none" stroke="#1a2238" stroke-width="${params.stroke}" stroke-opacity="0.5"/>`,
		);
	}
	const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${-FIELD / 2} ${-FIELD / 2} ${FIELD} ${FIELD}"><rect x="${-FIELD / 2}" y="${-FIELD / 2}" width="${FIELD}" height="${FIELD}" fill="#0b1020"/><g>${paths.join("")}</g></svg>`;
	const base64 = Buffer.from(svg, "utf-8").toString("base64");
	return `data:image/svg+xml;base64,${base64}`;
}

/** Serialize the data URI to the exact Biome-clean source text written to
 *  src/lib/guilloche-image.ts (a single const, trailing newline). */
export function serializeGuillocheImage(dataUri: string): string {
	return `// GENERATED by scripts/render-guilloche.ts — do not edit by hand.
// The prebaked engine-turned guilloché finish dial.ts paints as the production
// <image>; the live feTurbulence relief is the #debug alternative.

export const GUILLOCHE_IMAGE = ${JSON.stringify(dataUri)};
`;
}

if (import.meta.main) {
	const dataUri = buildGuillocheImage();
	const out = join(
		import.meta.dirname,
		"..",
		"src",
		"lib",
		"guilloche-image.ts",
	);
	writeGenerated(out, serializeGuillocheImage(dataUri));
}
