// Build-time generator: freezes the build-date geocentric positions into a TS
// literal so the shipped /astrolabe/ page reads current without recomputing the
// Meeus series at request time.
//
// PURE builder + write guard, exactly the scripts/sitemap.ts idiom: buildSnapshot
// reads only geocentricPositions (no I/O), so importing this module has no
// filesystem side effect; the writeFileSync runs only when this file is the entry
// point (import.meta.main). The build wires `node scripts/update-ephemeris-snapshot.ts`
// BEFORE the SSG render so src/lib/astro-snapshot.ts exists when page.ts's import
// chain (ephemeris.ts) pulls it in.
//
// The emitted literal MUST be Biome-clean (TABS, trailing newline) because
// `npm run check` lints src/. The generator builds the text with serializeSnapshot
// so the format is one place, asserted by the feature test.
import { join } from "node:path";
import type { BodyPosition } from "../src/lib/astro-math.ts";
import { geocentricPositions } from "../src/lib/astro-math.ts";
import { writeGenerated } from "./write-generated.ts";

/** The frozen build-date ephemeris: the ISO date it was computed for and the
 *  positions geocentricPositions returned for that date. Matches the shape
 *  ephemeris.ts reads back as the snapshot freshness layer. */
export interface AstroSnapshot {
	date: string;
	positions: BodyPosition[];
}

/** Build the snapshot for a date: the ISO date (YYYY-MM-DD) and the full set of
 *  geocentric body positions. PURE — no file write, so importing this module is
 *  side-effect free (the sitemap.ts purity invariant). */
export function buildSnapshot(date: Date): AstroSnapshot {
	return {
		date: date.toISOString().slice(0, 10),
		positions: geocentricPositions(date),
	};
}

/** Serialize a snapshot to the exact Biome-clean source text written to
 *  src/lib/astro-snapshot.ts (TABS via JSON.stringify indent "\t", trailing
 *  newline). The `satisfies` annotation keeps the literal typed against the
 *  AstroSnapshot shape ephemeris.ts imports without widening it. */
export function serializeSnapshot(snapshot: AstroSnapshot): string {
	const body = JSON.stringify(snapshot, null, "\t");
	return `// GENERATED by scripts/update-ephemeris-snapshot.ts — do not edit by hand.
// The frozen build-date ephemeris ephemeris.ts prefers as its freshness layer.
import type { AstroSnapshot } from "../../scripts/update-ephemeris-snapshot.ts";

export const ASTRO_SNAPSHOT = ${body} satisfies AstroSnapshot;
`;
}

if (import.meta.main) {
	const snapshot = buildSnapshot(new Date());
	const out = join(
		import.meta.dirname,
		"..",
		"src",
		"lib",
		"astro-snapshot.ts",
	);
	writeGenerated(out, serializeSnapshot(snapshot));
}
