// Ephemeris wrapper (PRODUCES Contract 1).
//
// The inline low-precision Meeus computation in astro-math.ts is the
// self-sufficient floor: ephemerisPositions ALWAYS returns a complete, correct
// set of body positions with no build artifact present. The build snapshot and a
// CDN override are ADDITIVE freshness layers layered on top of that floor:
//
//   - Build snapshot (src/lib/astro-snapshot.ts) — generated in Step 6 by
//     scripts/update-ephemeris-snapshot.ts. It freezes the build-date positions
//     so the shipped page reads current without recomputing at request time. It
//     is imported defensively (a dynamic seam), so this module typechecks and the
//     inline floor stands before the literal is generated.
//   - astronomia CDN override — a documented client-side seam (validated in the
//     build phase, not unit-tested) that can swap in higher-precision positions.
//
// Step 2 wires the floor. The snapshot/CDN seams are documented here and
// activated in Step 6, when astro-snapshot.ts exists.

import type { BodyPosition } from "../../lib/astro-math.ts";
import { geocentricPositions } from "../../lib/astro-math.ts";
import { ASTRO_SNAPSHOT } from "../../lib/astro-snapshot.ts";

/** Body positions for a date: inline Meeus base, snapshot/CDN as freshness
 *  layers. The inline base is self-sufficient; the freshness layers are additive
 *  and never required for a correct dial.
 *
 *  The build snapshot (src/lib/astro-snapshot.ts, generated by
 *  scripts/update-ephemeris-snapshot.ts at build time) is preferred when the
 *  requested date matches the build date, so the shipped page reads the exact
 *  build-day sky without recomputing the series. For any other date the inline
 *  Meeus floor recomputes — the snapshot never blocks a correct dial. */
export function ephemerisPositions(date: Date): BodyPosition[] {
	if (date.toISOString().slice(0, 10) === ASTRO_SNAPSHOT.date) {
		return ASTRO_SNAPSHOT.positions;
	}
	return geocentricPositions(date);
}
